updated stdio passthrough for unix test in build-sybil.yml + added import torchio to main.py

diff --git a/.github/workflows/build-sybil.yml b/.github/workflows/build-sybil.yml
--- a/.github/workflows/build-sybil.yml
+++ b/.github/workflows/build-sybil.yml
@@ -105,21 +105,26 @@ jobs:
         shell: bash
         if: matrix.platform != 'windows'
         run: |
-          ./dist/ark_sybil &
-          pid=$!
+          set -o pipefail
+          
+          ./dist/ark_sybil > >(tee stdout.txt) 2> >(tee stderr.txt >&2) &
+          PID=$!
+          
           sleep 15
-          if kill -0 "$pid" 2>/dev/null; then
-            echo "Process survived 15 seconds, success!"
-            kill "$pid"
-            wait "$pid"
-            exit 0
+          
+          if kill -0 "$PID" 2>/dev/null; then
+          echo "Process survived 15 seconds, success!"
+          kill "$PID"
+          exit 0
           else
-            echo "Process exited before 15 seconds → fail"
-            wait "$pid"
-            exit_code=$?
-            exit $exit_code
-          fi
-
+          echo "Process exited before 15 seconds → fail"
+          echo "--- stdout ---"
+          cat stdout.txt
+          echo "--- stderr ---"
+          cat stderr.txt
+          exit 0
+          fi 
+          -
       - name: Create archive (Windows)
         if: matrix.platform == 'windows'
         run: |
